# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    working_directory: /go/src/github.com/nektro/dacite
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: ./scripts/build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/
      - run: ./scripts/make_release.sh
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
